-- ──  INFRASTRUCTURE 

CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  COMMENT        = 'Warehouse for retail DWH loads and queries';
  

CREATE DATABASE IF NOT EXISTS RETAIL_DWH
  COMMENT = 'Retail transactions data warehouse';
  

CREATE SCHEMA IF NOT EXISTS RETAIL_DWH.STAR
  COMMENT = 'Star schema: fact + dimension tables';

USE WAREHOUSE RETAIL_WH;
USE DATABASE  RETAIL_DWH;
USE SCHEMA    STAR;

-- YEAR DIMENSION
CREATE TABLE DIM_YEAR (
    YEAR_KEY INT AUTOINCREMENT,
    YEAR_VALUE INT,
    PRIMARY KEY (YEAR_KEY)
);

-- MONTH DIMENSION
CREATE TABLE DIM_MONTH (
    MONTH_KEY INT AUTOINCREMENT,
    MONTH_VALUE INT,
    YEAR_KEY INT,
    PRIMARY KEY (MONTH_KEY),
    FOREIGN KEY (YEAR_KEY)
        REFERENCES DIM_YEAR(YEAR_KEY)
);

-- DATE DIMENSION
CREATE TABLE DIM_DATE (
    DATE_KEY INT AUTOINCREMENT,
    ORDER_DATE DATE,
    MONTH_KEY INT,
    PRIMARY KEY (DATE_KEY),
    FOREIGN KEY (MONTH_KEY)
        REFERENCES DIM_MONTH(MONTH_KEY)
);

-- CUSTOMER DIMENSION
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY INT AUTOINCREMENT,
    CUSTOMER_ID VARCHAR(20),
    GENDER VARCHAR(20),
    AGE INT,
    PRIMARY KEY (CUSTOMER_KEY)
);

-- CATEGORY DIMENSION
CREATE TABLE DIM_CATEGORY (
    CATEGORY_KEY INT AUTOINCREMENT,
    PRODUCT_CATEGORY VARCHAR(100),
    PRIMARY KEY (CATEGORY_KEY)
);

-- PRODUCT DIMENSION
CREATE TABLE DIM_PRODUCT (
    PRODUCT_KEY INT AUTOINCREMENT,
    CATEGORY_KEY INT,
    PRIMARY KEY (PRODUCT_KEY),
    FOREIGN KEY (CATEGORY_KEY)
        REFERENCES DIM_CATEGORY(CATEGORY_KEY)
);

-- FACT TABLE
CREATE TABLE FACT_SALES (
    TRANSACTION_ID INT,
    DATE_KEY INT,
    CUSTOMER_KEY INT,
    PRODUCT_KEY INT,
    QUANTITY INT,
    PRICE_PER_UNIT NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(10,2),

    FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY),

    FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);

INSERT INTO DIM_YEAR(YEAR_VALUE)
SELECT DISTINCT YEAR
FROM SALES_RAW;

INSERT INTO DIM_MONTH(MONTH_VALUE,YEAR_KEY)
SELECT DISTINCT
    S.MONTH,
    Y.YEAR_KEY
FROM SALES_RAW S
JOIN DIM_YEAR Y
ON S.YEAR = Y.YEAR_VALUE;

INSERT INTO DIM_DATE(ORDER_DATE,MONTH_KEY)
SELECT DISTINCT
    TO_DATE(ORDER_DATE,'DD-MM-YYYY'),
    M.MONTH_KEY
FROM SALES_RAW S
JOIN DIM_MONTH M
ON S.MONTH = M.MONTH_VALUE;

INSERT INTO DIM_CUSTOMER
(CUSTOMER_ID,GENDER,AGE)
SELECT DISTINCT
    CUSTOMER_ID,
    GENDER,
    TRY_TO_NUMBER(AGE)
FROM SALES_RAW;

INSERT INTO DIM_CATEGORY(PRODUCT_CATEGORY)
SELECT DISTINCT PRODUCT_CATEGORY
FROM SALES_RAW;

INSERT INTO DIM_PRODUCT(CATEGORY_KEY)
SELECT CATEGORY_KEY
FROM DIM_CATEGORY;


INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    DATE_KEY,
    CUSTOMER_KEY,
    PRODUCT_KEY,
    QUANTITY,
    PRICE_PER_UNIT,
    TOTAL_AMOUNT
)
SELECT
    S.TRANSACTION_ID,
    D.DATE_KEY,
    C.CUSTOMER_KEY,
    P.PRODUCT_KEY,
    TRY_TO_NUMBER(S.QUANTITY),
    S.PRICE_PER_UNIT,
    S.TOTAL_AMOUNT
FROM SALES_RAW S

JOIN DIM_CUSTOMER C
ON S.CUSTOMER_ID = C.CUSTOMER_ID

JOIN DIM_CATEGORY CAT
ON S.PRODUCT_CATEGORY = CAT.PRODUCT_CATEGORY

JOIN DIM_PRODUCT P
ON CAT.CATEGORY_KEY = P.CATEGORY_KEY

JOIN DIM_DATE D
ON TO_DATE(S.ORDER_DATE,'DD-MM-YYYY') = D.ORDER_DATE;